/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_17130655_proyecto_03;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class PB_17130655_Frame_03a extends javax.swing.JFrame {

    /**
     * Creates new form PB_17130655_Frame_03a
     */
    private Deporte [] depo = new Deporte[10];
    DefaultTableModel modelo;
    Ajedrez aj = new Ajedrez ();
    Beisbol ba = new Beisbol ();
    Boxeo bx = new Boxeo ();
    
    public PB_17130655_Frame_03a() {
        initComponents();
        modelo = (DefaultTableModel)jTabDeportes.getModel();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabDeportes = new javax.swing.JTable();
        jButDesfile = new javax.swing.JButton();
        jButDibujar = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jPAjedrez = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPBeisbol = new javax.swing.JPanel();
        jPBoxeo = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jTabDeportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null},
                {"", null, null},
                {"", null, null}
            },
            new String [] {
                "Deporte", "Estadio", "Tipo de Calificacion"
            }
        ));
        jScrollPane2.setViewportView(jTabDeportes);
        if (jTabDeportes.getColumnModel().getColumnCount() > 0) {
            jTabDeportes.getColumnModel().getColumn(2).setPreferredWidth(120);
        }

        jButDesfile.setText("Desfilar");
        jButDesfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesfileActionPerformed(evt);
            }
        });

        jButDibujar.setText("Dibujar");
        jButDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDibujarActionPerformed(evt);
            }
        });

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jPAjedrez.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPAjedrezLayout = new javax.swing.GroupLayout(jPAjedrez);
        jPAjedrez.setLayout(jPAjedrezLayout);
        jPAjedrezLayout.setHorizontalGroup(
            jPAjedrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPAjedrezLayout.setVerticalGroup(
            jPAjedrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_17130655_proyecto_03/PB_17130655_Asignacion_03.png"))); // NOI18N

        jPBeisbol.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPBeisbolLayout = new javax.swing.GroupLayout(jPBeisbol);
        jPBeisbol.setLayout(jPBeisbolLayout);
        jPBeisbolLayout.setHorizontalGroup(
            jPBeisbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPBeisbolLayout.setVerticalGroup(
            jPBeisbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPBoxeo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPBoxeoLayout = new javax.swing.GroupLayout(jPBoxeo);
        jPBoxeo.setLayout(jPBoxeoLayout);
        jPBoxeoLayout.setHorizontalGroup(
            jPBoxeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPBoxeoLayout.setVerticalGroup(
            jPBoxeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButEjemplo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButDesfile)
                                    .addComponent(jButDibujar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPAjedrez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPBeisbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPBoxeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButDesfile)
                            .addComponent(jButEjemplo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButDibujar)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPAjedrez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPBeisbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPBoxeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDibujarActionPerformed
        // TODO add your handling code here:
       //Ajedrez
       aj.dibujar(20, 5, jPAjedrez);
       String a1 = jTabDeportes.getValueAt(0, 1).toString();
       String a2 = jTabDeportes.getValueAt(0, 2).toString();
       String a3 = jTabDeportes.getValueAt(0, 0).toString();
       aj.setDescripcion(a3);
       aj.setEscenario(a1);
       aj.setTipoCalificacion(a2);
       
       //Beisbol
       String b2 = jTabDeportes.getValueAt(1, 0).toString();
       ba.setDescripcion(b2);
       ba.dibujar(20, 5, jPBeisbol);
       String f1 = jTabDeportes.getValueAt(1, 1).toString();
       ba.setEscenario(f1);
       ba.setNumJugadores("11");
       
       //Boxeo
       bx.dibujar(20, 5, jPBoxeo);
       String bx1 = jTabDeportes.getValueAt(2, 1).toString();
       String bx2 = jTabDeportes.getValueAt(2, 2).toString();
       String bx3 = jTabDeportes.getValueAt(2, 0).toString();
       bx.setDescripcion(bx3);
       bx.setEscenario(bx1);
       bx.setTipoCalificacion(bx2);
       bx.setLocutor("Julio Cesar Chavez Jr");
       
       
       jTextArea1.setText(aj.ver()+"\n "+ba.ver()+"\n "+bx.ver());
       
    }//GEN-LAST:event_jButDibujarActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        jTabDeportes.setValueAt("Ajedrez", 0, 0);
        jTabDeportes.setValueAt("Central Park NY", 0, 1);
        jTabDeportes.setValueAt("Beisbol",1, 0);
        jTabDeportes.setValueAt("AT&T Park,SF", 1, 1);
        jTabDeportes.setValueAt("Boxeo", 2, 0);
        jTabDeportes.setValueAt("MGM Grand Arena", 2, 1);
        jTabDeportes.setValueAt("Turnos", 0, 2);
        jTabDeportes.setValueAt("Puntaje", 1, 2);
        jTabDeportes.setValueAt("Puntos", 2, 2);
        
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ajDesc = jTabDeportes.getValueAt(0, 0).toString();
        String ajEsc = jTabDeportes.getValueAt(0,1).toString();
        String ajCalif = jTabDeportes.getValueAt(0,2).toString();
        aj.setDescripcion(ajDesc);
        aj.setEscenario(ajEsc);
        aj.setTipoCalificacion(ajCalif);
        
        
        String bsDesc = jTabDeportes.getValueAt(1, 0).toString();
        String bsEsc = jTabDeportes.getValueAt(1,1).toString();
        String bsCalif = jTabDeportes.getValueAt(1,2).toString();
        ba.setDescripcion(bsDesc);
        ba.setEscenario(bsEsc);
        ba.setNumJugadores("11");
        
        String bxDesc = jTabDeportes.getValueAt(2, 0).toString();
        String bxEsc = jTabDeportes.getValueAt(2,1).toString();
        String bxCalif = jTabDeportes.getValueAt(2,2).toString();
        bx.setDescripcion(bxDesc);
        bx.setEscenario(bxEsc);
        bx.setTipoCalificacion(bxCalif);
        
        jTextArea1.setText(aj.ver()+"\n "+ba.ver()+"\n "+bx.ver());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButDesfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesfileActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PB_17130655_Frame_03b abrir = new PB_17130655_Frame_03b(this);
        abrir.setVisible(true);
    }//GEN-LAST:event_jButDesfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_17130655_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_17130655_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_17130655_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_17130655_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_17130655_Frame_03a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButDesfile;
    private javax.swing.JButton jButDibujar;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPAjedrez;
    private javax.swing.JPanel jPBeisbol;
    private javax.swing.JPanel jPBoxeo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabDeportes;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
